server:
 port: 7902
spring:
 application:
  name: provider-sidecar
eureka:
 client:
  serviceUrl:
   defaultZone: http://user:password123@localhost:8761/eureka
logging:
 level:
  root: INFO
sidecar:
 port: 8060
 health-uri: http://localhost:8060/health.json
